; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
boards_dir = C:\Users\Exavyy\AppData\Local\Programs\Microsoft VS Code\boards

[env]
platform = espressif32 @ 6.10.0
framework = arduino
board_build.filesystem = littlefs
lib_ldf_mode = deep+
monitor_speed = 115200
build_flags = 
	-Isrc -Os
	-DARDUINOJSON_ENABLE_ARDUINO_PRINT=0
	-DARDUINOJSON_ENABLE_STD_STRING=0
	-DNDEBUG
lib_deps = 
	bodmer/TFT_eSPI @ 2.5.43
	bitbank2/AnimatedGIF @ 2.2.0

[env:esp32]
board = upesy_wrover
build_flags = ${env.build_flags}

monitor_port = COM3
monitor_speed = 115200